PROJECTS = {

    :ew => {:title=>"Castle.Facilities.EventWiring", :id=>"Castle.Facilities.EventWiring", :dir=>"Castle.Facilities.EventWiring", :test_dir=>"", :description=>"Castle Windsor is best of breed, mature Inversion of Control container available for .NET and Silverlight.", :authors=>"Castle Project Contributors", :company=>"Castleproject", :copyright=>"Copyright (c) Castle Project Contributors", :nuget_key=>"Castle.Facilities.EventWiring", :ruby_key=>"ew", :guid=>"7d1d0f78-d6ce-41a9-bebf-58cafa30bc76", :dependencies=>[], :create_package=>true},

    :fs => {:title=>"Castle.Facilities.FactorySupport", :id=>"Castle.Facilities.FactorySupport", :dir=>"Castle.Facilities.FactorySupport", :test_dir=>"", :description=>"Castle Windsor is best of breed, mature Inversion of Control container available for .NET and Silverlight.", :authors=>"Castle Project Contributors", :company=>"Castleproject", :copyright=>"Copyright (c) Castle Project Contributors", :nuget_key=>"Castle.Facilities.FactorySupport", :ruby_key=>"fs", :guid=>"d9550395-0721-44c0-a232-36db7f1e43fd", :dependencies=>[], :create_package=>true},

    :log => {:title=>"Castle.Facilities.Logging", :id=>"Castle.Facilities.Logging", :dir=>"Castle.Facilities.Logging", :test_dir=>"", :description=>"Castle Windsor is best of breed, mature Inversion of Control container available for .NET and Silverlight.", :authors=>"Castle Project Contributors", :company=>"Castleproject", :copyright=>"Copyright (c) Castle Project Contributors", :nuget_key=>"Castle.Facilities.Logging", :ruby_key=>"log", :guid=>"7fada49b-8d92-43ed-9346-cb391d182e64", :dependencies=>[], :create_package=>true},

    :rem => {:title=>"Castle.Facilities.Remoting", :id=>"Castle.Facilities.Remoting", :dir=>"Castle.Facilities.Remoting", :test_dir=>"", :description=>"Castle Windsor is best of breed, mature Inversion of Control container available for .NET and Silverlight.", :authors=>"Castle Project Contributors", :company=>"Castleproject", :copyright=>"Copyright (c) Castle Project Contributors", :nuget_key=>"Castle.Facilities.Remoting", :ruby_key=>"rem", :guid=>"c7d27e74-ca33-46c4-ad23-8b059561627e", :dependencies=>[], :create_package=>true},

    :syn => {:title=>"Castle.Facilities.Synchronize", :id=>"Castle.Facilities.Synchronize", :dir=>"Castle.Facilities.Synchronize", :test_dir=>"", :description=>"Castle Windsor is best of breed, mature Inversion of Control container available for .NET and Silverlight.", :authors=>"Castle Project Contributors", :company=>"Castleproject", :copyright=>"Copyright (c) Castle Project Contributors", :nuget_key=>"Castle.Facilities.Synchronize", :ruby_key=>"syn", :guid=>"ccf761a5-7f8e-4cf5-9cc2-d15d194dcd16", :dependencies=>[], :create_package=>true},

    :win => {:title=>"Castle.Windsor", :id=>"Castle.Windsor", :dir=>"Castle.Windsor", :test_dir=>"Castle.Windsor.Tests", :description=>"Castle Windsor is best of breed, mature Inversion of Control container available for .NET and Silverlight.", :authors=>"Castle Project Contributors", :company=>"Castleproject", :copyright=>"Copyright (c) Castle Project Contributors", :nuget_key=>"Castle.Windsor", :ruby_key=>"win", :guid=>"fb5c1d37-a316-444a-b4cf-2b8b17ffbbe1", :dependencies=>[], :create_package=>true},

}